### ISSUE TITLE
生产环境中grunt报错 Uglifying source .tmp/public/concat/production.js failed.

### ISSUE THREAD

**Issue by canfeit** [linksgo2011/nodecms#6]
Warning: connect.session() MemoryStore is not
designed for a production environment, as it will leak
memory, and will not scale past a single process.
*\* Grunt :: An error occurred. **
## error:

Aborted due to warnings.
Running "uglify:dist" (uglify) task
JS_Parse_Error {
  message: 'Unexpected token: punc ({)',
  filename: '../concat/production.js',
  line: 1815,
  col: 10,
  pos: 156176,
  stack: 'Error\n    at new JS_Parse_Error (eval at <anonymous> (nodecms\node_modules\grunt-contrib-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1526:18)\n    at js_err
or (eval at <anonymous> (nodecms\node_modules\grunt-contrib-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:1534:11)\n    at croak (eval at <anonymous> (nodecms\node_modules\grunt-contrib-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2025:9)\n    at token_error (eval at <anonymous> (nodecms\node_modules\
grunt-contrib-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2033:9)\n    at unexpected (eval at <anonymous> (nodecms\node_modules\grunt-contrib-uglify\node_modules\ugl
ify-js\tools\node.js:22:1), <anonymous>:2039:9)\n    at semicolon (eval at <anonymous> (nodecms\node_modules\grunt-contrib-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous

> :2059:43)\n    at eval (eval at <anonymous> (nodecms\node_modules\grunt-contrib-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2193:38)\n    at eval (eval at <anonymous>
>  (nodecms\node_modules\grunt-contrib-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2072:24)\n    at block_ (eval at <anonymous> (nodecms
> \node_modules\grunt-contrib-uglify\node_modules\uglify-js\tools\node.js:22:1), <anonymous>:2352:20)\n    at eval (eval at <anonymous> (nodecms\node_modules\grunt-contrib-uglify\node_m
> odules\uglify-js\tools\node.js:22:1), <anonymous>:2325:25)' }
> 
> > Uglifying source .tmp/public/concat/production.js failed.
> > Warning: Uglification failed.
> > Unexpected token: punc ({).
> > Line 1815 in .tmp/public/concat/production.js

---

error: Looks like a Grunt error occurred--
error: Please fix it, then **restart Sails** to continue running tasks (e.g. watching for changes in assets)
error: Or if you're stuck, check out the troubleshooting tips below.

error: Troubleshooting tips:
error:
error:  *-> Are "grunt" and related grunt task modules installed locally?  Run `npm install` if you're not sure.
error:
error:  *-> You might have a malformed LESS, SASS, CoffeeScript file, etc.
error:
error:  *-> Or maybe you don't have permissions to access the `.tmp` directory?
error:      e.g., `nodecms\.tmp` ?
error:
error:      If you think this might be the case, try running:
error:      sudo chown -R YOUR_COMPUTER_USER_NAME nodecms.tmp

Error: The hook `grunt` is taking too long to load.
Make sure it is triggering its `initialize()` callback, or else set `sails.config.grunt._hookTimeout to a higher value (currently 20000)
    at tooLong [as _onTimeout] (nodecms\node_modules\sails\lib\app\private\loadHooks.js:85:21)
    at Timer.listOnTimeout (timers.js:92:15) { [Error: The hook`grunt`is taking too long to load.
Make sure it is triggering its`initialize()`callback, or else set`sails.config.grunt._hookTimeout to a higher value (currently 20000)] code: 'E_HOOK_TIMEOUT' }

**Comment by canfeit** [comment]
不知道是不是跟我的运行环境有关，劳烦作者查看一下。
