### ISSUE TITLE
启动项目报错

### ISSUE THREAD

**Issue by yunzaifei** [linksgo2011/nodecms#9]
错误信息如下：
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: listen EACCES 0.0.0.0:80
    at Object.exports._errnoException (util.js:870:11)
    at exports._exceptionWithHostPort (util.js:893:20)
    at Server._listen2 (net.js:1224:19)
    at listen (net.js:1273:10)
    at Server.listen (net.js:1369:5)
    at Array.async.auto.start (E:\GitHub Project\nodecms\node_modules\sails\lib\
hooks\http\start.js:29:35)
    at E:\GitHub Project\nodecms\node_modules\async\lib\async.js:484:38
    at _each (E:\GitHub Project\nodecms\node_modules\async\lib\async.js:46:13)
    at Object.async.auto (E:\GitHub Project\nodecms\node_modules\async\lib\async
.js:455:9)
    at Sails.startServer (E:\GitHub Project\nodecms\node_modules\sails\lib\hooks
\http\start.js:16:11)
    at emitNone (events.js:67:13)
    at Sails.emit (events.js:166:7)
    at Sails.emitter.emit (E:\GitHub Project\nodecms\node_modules\sails\lib\app\
private\after.js:50:11)
    at afterBootstrap (E:\GitHub Project\nodecms\node_modules\sails\lib\app\priv
ate\initialize.js:56:11)
    at bootstrapDone (E:\GitHub Project\nodecms\node_modules\sails\lib\app\priva
te\bootstrap.js:51:14)
    at Object.module.exports.bootstrap (E:\GitHub Project\nodecms\config\bootstr
ap.js:16:3)

**Comment by linksgo2011** [comment]
@yunzaifei  使用管理员权限启动，或检查端口是否被占用 

`Error: listen EACCES 0000:80`

**Comment by yunzaifei** [comment]
修改端口号是在../config/env/production.js文件中修改为：
module.exports = {

  /***************************************************************************
- Set the default database connection for models in the production        *
- environment (see config/connections.js and config/models.js )           *
  ***************************************************************************/
  
  // models: {
  //   connection: 'someMysqlServer'
  // },
  
  /***************************************************************************
- Set the port in the production environment to 80                        *
  ***************************************************************************/
  
  port: 4000,
  
  /***************************************************************************
- Set the log level in production environment to "silent"                 *
  ***************************************************************************/
  
  // log: {
  //   level: "silent"
  // }

};
不知道我理解的对不对。

**Comment by linksgo2011** [comment]
对的

**Comment by yunzaifei** [comment]
可是我修改了以后，还是报同样的错误，
 Error: listen EACCES 0000:80

**Comment by linksgo2011** [comment]
使用管理员权限，看下是不是被其他程序占用了

**Comment by yunzaifei** [comment]
看过了，端口号改成4000以后，端口4000没有被占用，并且报的错误还是
Error: listen EACCES 0000:80 ，跟没改端口号效果一样。

**Comment by linksgo2011** [comment]
env下两个文件，看你是什么环境进行修改

**Comment by yunzaifei** [comment]
是在windows7上运行，两个文件都增加了port: 4000,的字段，仍然报Error: listen EACCES 0000:80

**Comment by simdm** [comment]
修改config/local.js

**Comment by linksgo2011** [comment]
@yunzaifei  注意权限

**Comment by yunzaifei** [comment]
@simdm，谢谢。修改了config/local.js里的“ port: process.env.PORT || 3000,”语句后就可以了。
